"""The cohaera_tool activity record: one durable fact per tool call.

This is the fact stream, kept apart from the session verdict the way conn.log
is kept apart from notice.log. These tests are its acceptance gate: every
field is generated by a fixture and consumed by a hunt query here, its null
semantics are asserted, and the record is shown to join back to its verdict.

The three HUNT functions are the point. A cohaera_tool row that no query reads
is a field nobody asked for; each hunt below is a question a SOC actually asks,
answered against the rows with no detection loaded.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from cohaera.checks import run_all  # noqa: E402
from cohaera.ingest import load  # noqa: E402
from cohaera.model import TOOL_SCHEMA, to_cim_event, to_tool_events  # noqa: E402

HOST = {"host_name": "h1", "host_ip": "10.0.0.1"}


def _ev(sid, ts, etype, *, tool=None, span=None, **data):
    return {
        "timestamp": round(ts, 3),
        "trace_id": sid,
        "session_id": sid,
        "span_id": span,
        "event_type": etype,
        "agent_name": "agent-a",
        "tool_name": tool,
        "framework": "claude",
        "data": {"log_source_type": "observra", **data},
        **HOST,
    }


def _controlled(sid: str) -> list[dict]:
    """One session that exercises every pairing state a hunt cares about.

    read-only paired, consequential paired (no approval, no receipt),
    consequential unpaired (start with no terminal), and an orphan terminal.
    """
    return [
        # read-only, paired and complete
        _ev(sid, 1.0, "tool_start", tool="search_docs", span="sp1", reversible=True,
            tool_args={"q": "x"}),
        _ev(sid, 1.4, "tool_end", tool="search_docs", span="sp1", reversible=True,
            result="success", duration_ms=400),
        # consequential, paired and complete, unapproved, no receipt
        _ev(sid, 2.0, "tool_start", tool="send_email", span="sp2", reversible=False,
            tool_args={"to": "a@b"}),
        _ev(sid, 2.5, "tool_end", tool="send_email", span="sp2", reversible=False,
            result="success", duration_ms=500),
        # consequential, unpaired: a start with no terminal event
        _ev(sid, 3.0, "tool_start", tool="deploy_release", span="sp3",
            reversible=False, tool_args={"env": "prod"}),
        # orphan terminal: a terminal with no matching start
        _ev(sid, 4.0, "tool_end", tool="ghost_tool", span="sp9", result="success"),
    ]


def _load_one(tmp_path: Path, rows: list[dict], name: str = "t.jsonl"):
    p = tmp_path / name
    p.write_text("\n".join(json.dumps(r) for r in rows) + "\n", encoding="utf-8")
    sessions = load(str(p))
    assert len(sessions) == 1
    return sessions[0]


# ---------------------------------------------------------------------------
# Structure and invariants
# ---------------------------------------------------------------------------

def test_one_row_per_tool_call(tmp_path):
    s = _load_one(tmp_path, _controlled("s1"))
    rows = to_tool_events(s)
    assert len(rows) == len(s.tool_calls)
    assert len(rows) == 4
    for r in rows:
        assert r["type"] == "cohaera_tool"
        assert r["schema"] == TOOL_SCHEMA
        assert r["session_id"] == "s1"


def test_rows_carry_their_own_identity_and_the_states(tmp_path):
    s = _load_one(tmp_path, _controlled("s1"))
    by_tool = {r["data"]["tool"]: r for r in to_tool_events(s)}

    ro = by_tool["search_docs"]["data"]
    assert ro["class"] == "read_only"
    assert ro["consequential"] is False
    assert ro["state"] == "complete"
    assert ro["executed"] is True

    email = by_tool["send_email"]["data"]
    assert email["consequential"] is True
    assert email["state"] == "complete"
    assert email["result"] == "success"
    assert email["approval_state"] == "none"
    assert email["receipt_present"] is False
    assert email["receipt_binding"] == "unbound"


def test_null_semantics_of_an_unpaired_call(tmp_path):
    s = _load_one(tmp_path, _controlled("s1"))
    deploy = next(r["data"] for r in to_tool_events(s)
                  if r["data"]["tool"] == "deploy_release")
    # A start with no terminal: open, and result/ended_at are NULL, never 0 or
    # "failure". Absence of a terminal is not a failure.
    assert deploy["state"] == "open"
    assert deploy["result"] is None
    assert deploy["ended_at"] is None
    assert deploy["executed"] is False
    assert deploy["consequential"] is True


def test_orphan_terminal_is_a_row(tmp_path):
    s = _load_one(tmp_path, _controlled("s1"))
    ghost = next((r["data"] for r in to_tool_events(s)
                  if r["data"]["tool"] == "ghost_tool"), None)
    assert ghost is not None, "a terminal with no start must still be a row"
    assert ghost["state"] in {"orphan_end", "mismatched_end", "duplicate_end"}


def test_tool_event_id_is_deterministic(tmp_path):
    s = _load_one(tmp_path, _controlled("s1"))
    prov = {"analysis_run_id": "run-1"}
    a = [r["tool_event_id"] for r in to_tool_events(s, provenance=prov)]
    b = [r["tool_event_id"] for r in to_tool_events(s, provenance=prov)]
    assert a == b
    assert len(set(a)) == len(a), "ids must be unique within a session"


def test_rows_join_to_their_session_verdict(tmp_path):
    s = _load_one(tmp_path, _controlled("s1"))
    findings, cov = run_all(s)
    prov = {"analysis_run_id": "run-1", "detector_version": "0.3.0"}
    verdict = to_cim_event(s, findings, coverage=cov, provenance=prov)
    rows = to_tool_events(s, provenance=prov, verdict_id=verdict["verdict_id"])
    for r in rows:
        assert r["verdict_id"] == verdict["verdict_id"]
        assert r["data"]["provenance"]["analysis_run_id"] == "run-1"


# ---------------------------------------------------------------------------
# The hunts. Each is a question a SOC asks of the activity log directly.
# ---------------------------------------------------------------------------

def hunt_unapproved_consequential(rows):
    """Consequential actions that COMPLETED without a binding approval."""
    return [r for r in rows if r["data"]["consequential"]
            and r["data"]["executed"]
            and r["data"]["approval_state"] != "covered"]


def hunt_success_without_bound_receipt(rows):
    """A consequential success whose effect is not backed by a bound receipt --
    the agent's own word for what it did, unverifiable against the target."""
    return [r for r in rows if r["data"]["consequential"]
            and r["data"]["result"] == "success"
            and r["data"]["receipt_binding"] != "bound"]


def hunt_unpaired_consequential(rows):
    """A consequential call that started and never terminated."""
    return [r for r in rows if r["data"]["consequential"]
            and r["data"]["state"] == "open"]


def test_hunt_unapproved_consequential(tmp_path):
    s = _load_one(tmp_path, _controlled("s1"))
    rows = to_tool_events(s)
    hits = {r["data"]["tool"] for r in hunt_unapproved_consequential(rows)}
    # send_email completed unapproved; deploy_release never completed, so it is
    # not an executed action and must not appear here.
    assert "send_email" in hits
    assert "deploy_release" not in hits
    assert "search_docs" not in hits


def test_hunt_success_without_bound_receipt(tmp_path):
    s = _load_one(tmp_path, _controlled("s1"))
    hits = {r["data"]["tool"]
            for r in hunt_success_without_bound_receipt(to_tool_events(s))}
    assert "send_email" in hits
    assert "search_docs" not in hits, "read-only work is not the target"


def test_hunt_unpaired_consequential(tmp_path):
    s = _load_one(tmp_path, _controlled("s1"))
    hits = {r["data"]["tool"]
            for r in hunt_unpaired_consequential(to_tool_events(s))}
    assert hits == {"deploy_release"}


# ---------------------------------------------------------------------------
# The approval and receipt fields are wired to real evidence, not defaulted.
# Proven against committed fixtures that carry each.
# ---------------------------------------------------------------------------

def _rows_for(path: str):
    out = []
    for s in load(str(REPO / path)):
        out.extend(to_tool_events(s))
    return out


def test_approval_state_reflects_a_real_covering_approval():
    rows = _rows_for("demo/approval-replay/telemetry.jsonl")
    states = {r["data"]["approval_state"] for r in rows}
    assert "covered" in states, (
        "the approval-replay demo carries a covering approval; approval_state "
        "must read it, not default to none")


def test_receipt_binding_reflects_a_real_receipt():
    rows = _rows_for("lab/local/runs/latest/inputs/04-contradiction.jsonl")
    assert any(r["data"]["receipt_present"] for r in rows)
    assert any(r["data"]["receipt_binding"] == "bound" for r in rows), (
        "the contradiction fixture binds a receipt exactly; receipt_binding "
        "must read it")
