#!/usr/bin/env python3
# Copyright 2026 Imran Hafeez
# SPDX-License-Identifier: Apache-2.0
"""Generate and check the frozen CH06 conformance matrix.

    python lab/ch06/run.py
    python lab/ch06/run.py --check

The expectations file is hand-written and is never generated by this script.
Fixtures are derived from one pristine signed stream, mutations are applied only
after signing, and the same bytes are scored by Cohaera and by baseline.py.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(HERE))

from baseline import BaselineResult  # noqa: E402
from baseline import verify as baseline_verify  # noqa: E402

from cohaera import ed25519  # noqa: E402
from tools.collector_sign import (  # noqa: E402
    key_id_for,
    keys_document,
    sign_stream,
)

LAB_SEED = bytes.fromhex("6d" * 32)
PUBLIC_KEY = ed25519.public_key(LAB_SEED)
KEY_ID = key_id_for(PUBLIC_KEY)
STREAM_ID = "ch06-conformance-stream"
BASE = 1_785_720_000.0
AS_OF = BASE + 600.0
MAX_AGE = 3_600.0
CASE_NAMES = (
    "intact", "deleted", "modified", "stripped", "reordered",
    "truncated", "replayed", "no_key", "unsupported",
)


def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode()


def _jsonl_bytes(records: list[dict[str, Any]]) -> bytes:
    return "".join(
        json.dumps(record, sort_keys=True) + "\n" for record in records
    ).encode()


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _sha256(path: Path) -> str:
    return _sha256_bytes(path.read_bytes())


def _write(path: Path, value: bytes) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(value)
    return path


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def _event(seq: int, session_id: str, event_type: str,
           data: dict[str, Any]) -> dict[str, Any]:
    return {
        "agent_name": "ch06-lab-agent",
        "data": data,
        "event_id": f"ch06-{seq}",
        "event_type": event_type,
        "framework": "lab",
        "host": "collector-boundary",
        "session_id": session_id,
        "timestamp": BASE + seq,
        "trace_id": session_id,
    }


def _canonical_records() -> list[dict[str, Any]]:
    """One stream with the F05 boundary between sequence 2 and sequence 3."""
    return [
        _event(0, "target", "session_start", {"action": "start_session"}),
        _event(1, "target", "agent_start", {"action": "invoke_agent"}),
        _event(2, "target", "model_response", {
            "action": "model_response", "response_text": "Original answer.",
        }),
        _event(3, "other", "session_start", {"action": "start_session"}),
        _event(4, "other", "agent_start", {"action": "invoke_agent"}),
        _event(5, "other", "session_end", {"action": "end_session"}),
    ]


def _build_fixtures() -> tuple[
        list[dict[str, Any]], list[dict[str, Any]],
        dict[str, list[dict[str, Any]]]]:
    raw = _canonical_records()
    pristine = sign_stream(
        raw, STREAM_ID, LAB_SEED, KEY_ID, sign_every=100,
    )
    cases = {name: copy.deepcopy(pristine) for name in CASE_NAMES}

    cases["deleted"] = [
        record for record in cases["deleted"]
        if record["integrity"]["seq"] != 2
    ]
    cases["modified"][2]["data"]["response_text"] = "Changed answer."
    cases["stripped"][2]["data"]["response_text"] = "Changed answer."
    cases["stripped"][2]["integrity"].pop("prev")
    cases["stripped"][2]["integrity"].pop("chain")
    cases["reordered"] = [
        cases["reordered"][index] for index in (0, 2, 1, 3, 5, 4)
    ]
    cases["truncated"] = cases["truncated"][:-1]
    for record in cases["unsupported"]:
        record["integrity"]["scheme"] = "cohaera.integrity:2"
    return raw, pristine, cases


def _score(fixture: Path, *, trust_store: Path | None,
           ledger: Path) -> tuple[int, list[dict[str, Any]], str]:
    argv = [
        sys.executable, "-m", "cohaera.cli", "score", str(fixture),
        "--evidence-max-age", str(MAX_AGE),
        "--evidence-as-of", str(AS_OF),
        "--seen-streams", str(ledger),
    ]
    if trust_store is not None:
        argv += ["--trust-store", str(trust_store)]
    env = dict(os.environ, PYTHONPATH=str(REPO / "src"))
    process = subprocess.run(
        argv, cwd=REPO, env=env, capture_output=True, text=True,
        timeout=60, check=False,
    )
    records = [
        json.loads(line) for line in process.stdout.splitlines() if line.strip()
    ]
    return process.returncode, records, process.stderr


def _ch06_contract(record: dict[str, Any]) -> dict[str, Any]:
    checks = record["data"]["coverage"]["checks"]
    return next(check for check in checks
                if check["check"] == "CH06_evidence_integrity")


def _summarise_cohaera(records: list[dict[str, Any]]) -> dict[str, Any]:
    sessions: dict[str, Any] = {}
    for record in sorted(records, key=lambda item: item["session_id"]):
        contract = _ch06_contract(record)
        findings = record["data"].get("findings", [])
        integrity: dict[str, Any] = {}
        for finding in findings:
            if finding.get("check") == "CH06_evidence_integrity":
                candidate = finding.get("evidence", {}).get("integrity", {})
                if isinstance(candidate, dict):
                    integrity = candidate
        sessions[record["session_id"]] = {
            "ch06_confidence": round(float(contract["confidence"]), 4),
            "ch06_fired": any(
                finding.get("check") == "CH06_evidence_integrity"
                for finding in findings
            ),
            "ch06_reasons": sorted(contract["reasons"]),
            "ch06_status": contract["status"],
            "evidence_status": record["data"]["coverage"]["evidence_status"],
            "integrity_codes": sorted(integrity.get("codes", {})),
        }
    return {"sessions": sessions}


def _cohaera_projection(actual: dict[str, Any]) -> dict[str, Any]:
    sessions = actual["sessions"]
    return {
        "ch06_fired_sessions": sorted(
            session_id for session_id, value in sessions.items()
            if value["ch06_fired"]
        ),
        "ch06_status": {
            session_id: value["ch06_status"]
            for session_id, value in sessions.items()
        },
        "evidence_status": {
            session_id: value["evidence_status"]
            for session_id, value in sessions.items()
        },
    }


def _cohaera_matches(actual: dict[str, Any], expected: dict[str, Any]) -> bool:
    outcome = {
        key: value for key, value in expected.items()
        if key != "required_reasons"
    }
    if _cohaera_projection(actual) != outcome:
        return False
    sessions = actual["sessions"]
    return all(
        set(reasons).issubset(sessions[session_id]["ch06_reasons"])
        for session_id, reasons in expected.get("required_reasons", {}).items()
    )


def _baseline_for(case: str, records: list[dict[str, Any]]) -> BaselineResult:
    public_key = None if case == "no_key" else PUBLIC_KEY
    seen: dict[str, tuple[int, int, str]] = {}
    if case == "replayed":
        baseline_verify(records, public_key=public_key, seen=seen)
    return baseline_verify(records, public_key=public_key, seen=seen)


def _baseline_projection(actual: dict[str, Any]) -> dict[str, Any]:
    return {
        "affected_sessions": actual["affected_sessions"],
        "issues": actual["issues"],
        "records_reordered": actual["records_reordered"],
        "status": actual["status"],
    }


def _results_markdown(results: dict[str, Any]) -> str:
    lines = [
        "# CH06 conformance results",
        "",
        "Every case is derived from the same pristine signed stream. `PASS`",
        "means both Cohaera and the independent baseline matched the",
        "predeclared expectations in `expectations.json`.",
        "",
        "| Case | Condition | Cohaera evidence (target / other) | CH06 "
        "(target / other) | Baseline | Result |",
        "|---|---|---|---|---|---|",
    ]
    for case in CASE_NAMES:
        result = results["cases"][case]
        sessions = result["cohaera"]["sessions"]
        evidence = " / ".join(
            sessions[key]["evidence_status"] for key in ("target", "other")
        )
        contracts = " / ".join(
            sessions[key]["ch06_status"] for key in ("target", "other")
        )
        outcome = "PASS" if result["expectation_met"] else "FAIL"
        lines.append(
            f"| `{case}` | `{result['condition']}` | `{evidence}` | "
            f"`{contracts}` | `{result['baseline']['status']}` | **{outcome}** |"
        )
    summary = results["summary"]
    lines += [
        "",
        "## Acceptance checks",
        "",
        f"- Expectations met: **{summary['expectations_met']} of "
        f"{summary['cases']}**",
        "- Manipulated affected sessions reported `verified_complete`: "
        f"**{summary['manipulated_verified_complete']}**",
        "- Intact or reorder-only sessions reported inadmissible: "
        f"**{summary['benign_inadmissible']}**",
        "- Missing or unsupported cases explicitly declined/degraded: "
        f"**{summary['explicit_declines']} of 2**",
        "",
    ]
    return "\n".join(lines)


def _compare_tree(expected: Path, actual: Path) -> list[str]:
    expected_files = {
        path.relative_to(expected): path.read_bytes()
        for path in expected.rglob("*") if path.is_file()
    }
    actual_files = {
        path.relative_to(actual): path.read_bytes()
        for path in actual.rglob("*") if path.is_file()
    }
    problems: list[str] = []
    for path in sorted(expected_files.keys() | actual_files.keys()):
        if path not in expected_files:
            problems.append(f"unexpected generated file: {path}")
        elif path not in actual_files:
            problems.append(f"missing generated file: {path}")
        elif expected_files[path] != actual_files[path]:
            problems.append(f"generated file differs: {path}")
    return problems


def _generate(destination: Path) -> dict[str, Any]:
    expectations = json.loads((HERE / "expectations.json").read_text())
    raw, pristine, cases = _build_fixtures()
    source = destination / "fixtures" / "source"
    case_dir = destination / "fixtures" / "cases"
    _write(source / "canonical.raw.jsonl", _jsonl_bytes(raw))
    _write(source / "canonical.signed.jsonl", _jsonl_bytes(pristine))
    trust_store = _write(
        source / "trust-store.json",
        _json_bytes(keys_document(PUBLIC_KEY, KEY_ID)),
    )
    fixture_paths = {
        case: _write(case_dir / f"{case}.jsonl", _jsonl_bytes(records))
        for case, records in cases.items()
    }

    result_cases: dict[str, Any] = {}
    with tempfile.TemporaryDirectory(prefix="cohaera-ch06-ledgers-") as temp:
        ledgers = Path(temp)
        for case in CASE_NAMES:
            fixture = fixture_paths[case]
            ledger = ledgers / f"{case}.json"
            store = None if case == "no_key" else trust_store
            if case == "replayed":
                first_code, _, first_stderr = _score(
                    fixture, trust_store=store, ledger=ledger,
                )
                if first_code != 0:
                    raise RuntimeError(
                        f"replay seed pass failed ({first_code}): {first_stderr}"
                    )
            code, verdicts, stderr = _score(
                fixture, trust_store=store, ledger=ledger,
            )
            if not verdicts:
                raise RuntimeError(
                    f"{case}: Cohaera emitted no verdicts (exit {code}): {stderr}"
                )
            cohaera = _summarise_cohaera(verdicts)
            fixture_records = _read_jsonl(fixture)
            baseline = _baseline_for(case, fixture_records).as_dict()
            expected = expectations["cases"][case]
            expectation_met = (
                _cohaera_matches(cohaera, expected["cohaera"])
                and _baseline_projection(baseline) == expected["baseline"]
            )
            result_cases[case] = {
                "baseline": baseline,
                "cohaera": {"exit_code": code, **cohaera},
                "condition": expected["condition"],
                "expectation_met": expectation_met,
                "input_bytes": fixture.stat().st_size,
                "input_sha256": _sha256(fixture),
                "mutation": expected["mutation"],
                "records": len(fixture_records),
            }

    manipulated_verified = 0
    benign_inadmissible = 0
    explicit_declines = 0
    for case, result in result_cases.items():
        expected = expectations["cases"][case]
        sessions = result["cohaera"]["sessions"]
        if expected["condition"] == "manipulated":
            manipulated_verified += sum(
                sessions[session_id]["evidence_status"] == "verified_complete"
                for session_id in expected["affected_sessions"]
            )
        if expected["condition"] in {"intact", "benign_transport"}:
            benign_inadmissible += sum(
                value["evidence_status"] == "inadmissible"
                for value in sessions.values()
            )
        if case in {"no_key", "unsupported"}:
            explicit_declines += int(all(
                value["ch06_status"] in {"degraded", "not_evaluated"}
                for value in sessions.values()
            ))

    results = {
        "cases": result_cases,
        "schema": "cohaera.ch06_results:1",
        "summary": {
            "benign_inadmissible": benign_inadmissible,
            "cases": len(result_cases),
            "expectations_met": sum(
                result["expectation_met"] for result in result_cases.values()
            ),
            "explicit_declines": explicit_declines,
            "manipulated_verified_complete": manipulated_verified,
        },
    }
    latest = destination / "runs" / "latest"
    results_path = _write(latest / "results.json", _json_bytes(results))
    markdown_path = _write(
        latest / "RESULTS.md", _results_markdown(results).encode(),
    )
    fixture_digests = {
        str(path.relative_to(destination)): _sha256(path)
        for path in sorted((destination / "fixtures").rglob("*.json*"))
    }
    manifest = {
        "artifacts": {
            "runs/latest/RESULTS.md": _sha256(markdown_path),
            "runs/latest/results.json": _sha256(results_path),
        },
        "cases": len(result_cases),
        "expectations_sha256": _sha256(HERE / "expectations.json"),
        "fixtures": fixture_digests,
        "schema": "cohaera.ch06_run_manifest:1",
    }
    _write(latest / "RUN-MANIFEST.json", _json_bytes(manifest))
    return results


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true",
        help="fail if regenerated fixtures or results differ from the commit",
    )
    args = parser.parse_args(argv)
    started = time.monotonic()

    if args.check:
        with tempfile.TemporaryDirectory(prefix="cohaera-ch06-check-") as temp:
            generated = Path(temp)
            results = _generate(generated)
            problems = (
                _compare_tree(HERE / "fixtures", generated / "fixtures")
                + _compare_tree(HERE / "runs" / "latest",
                                generated / "runs" / "latest")
            )
        if problems:
            print("ch06 lab differs from the committed run:", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            print("Run: python lab/ch06/run.py", file=sys.stderr)
            return 1
        action = "matches the committed matrix"
    else:
        for path in (HERE / "fixtures", HERE / "runs" / "latest"):
            shutil.rmtree(path, ignore_errors=True)
        results = _generate(HERE)
        action = "wrote fixtures and runs/latest"

    summary = results["summary"]
    elapsed = time.monotonic() - started
    print(
        f"lab/ch06: {summary['expectations_met']}/{summary['cases']} cases "
        f"{action} ({elapsed:.1f}s, python "
        f"{sys.version_info.major}.{sys.version_info.minor})"
    )
    return 0 if summary["expectations_met"] == summary["cases"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
